# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/cc3b9ef8-b1c1-4f09-b2ae-6c5b8524cf3c";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5A5C-C6C5";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/storage" =
    { device = "/dev/disk/by-uuid/9803fd01-2d59-4b2b-b146-7feda4f4d779";
      fsType = "ext4";
      options = [ "defaults" "nofail" "x-systemd.automount" "x-systemd.device-timeout=10s" ];
    };

  fileSystems."/mnt/win-storage" =
    { device = "/dev/disk/by-uuid/7694F19E94F160D3";
      fsType = "ntfs";
      options = [ "defaults" "nofail" "x-systemd.automount" "x-systemd.device-timeout=10s" ];
    };

  systemd.tmpfiles.rules = [
    "d /storage 0755 ivopiro users -"
    "d /win-storage 0755 ivopiro users -"
  ];

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
