theme = "ayu_mirage"

[editor]
line-number = "relative"
bufferline = "always"

[editor.statusline]
left = ["mode", "spinner", "file-absolute-path", "diagnostics"]
right = ["file-type", "file-encoding", "position"]

[keys.normal.g]
"u" = "switch_to_lowercase"
"U" = "switch_to_uppercase"

[keys.select.g]
"u" = "switch_to_lowercase"
"U" = "switch_to_uppercase"
